name: Zerocode OpenAPI Generator POC

on:
  workflow_dispatch:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setting up JDK8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Building and testing the changes
        run: mvn install -ntp -DskipTests=true && mvn test -ntp -pl zerocode-openapi
